import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import Layout from 'components/Layout';
import Link from 'next/link';
import { postsService } from 'api/index';
import { Posts } from '@types';
import dayjs from 'dayjs';
import Header from 'components/Header';

export const getServerSideProps: GetServerSideProps = async () => {
	const ret = await postsService.getAll();
	return {
		props: {
			posts: ret.data,
		},
	};
};

const Home: NextPage<{
	posts: Pick<Posts, 'article_key' | 'id' | 'create_time' | 'title'>[];
}> = ({ posts }) => {
	return (
		<Layout>
			<Head>
				<title>井底之蛙的一片天空</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<div className='text-sm mt-6 space-y-1 '>
				{posts.map((item) => {
					return (
						<Link key={item.id} href={`/posts/${item.article_key}`} passHref>
							<a className='group  py-1 block text-gray-700 underline-offset-1 hover:text-gray-900'>
								<span className='group-hover:underline '>{item.title}</span>
								<span className='text-xs ml-8 text-gray-400'>
									{dayjs(item.create_time).format('YYYY / MM / DD')}
								</span>
							</a>
						</Link>
					);
				})}
			</div>
		</Layout>
	);
};

export default Home;
