import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import Layout from 'components/Layout';
import Link from 'next/link';
import { postsService } from 'api/index';
import { Posts } from '@types';
import dayjs from 'dayjs';
import Header from 'components/Header';

export const getServerSideProps: GetServerSideProps = async () => {
	const ret = await postsService.getAll();
	ret.data = ret.data.map((item) => {
		item.create_time = dayjs(item.create_time).format('YYYY / MM / DD');
		return item;
	});
	return {
		props: {
			posts: ret.data,
		},
	};
};

const Home: NextPage<{
	posts: Pick<Posts, 'article_key' | 'id' | 'create_time' | 'title'>[];
}> = ({ posts }) => {
	return (
		<Layout>
			<Head>
				<title>鼠人苦工的博客</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<div className='text-base  mt-6 font-fusion md:space-y-1.5 space-y-4'>
				{posts.map((item) => {
					return (
						<Link key={item.id} href={`/posts/${item.article_key}`} passHref>
							<a className='group px-2 md:px-0 md:py-1 md:text-left text-center  leading-snug  block md:flex items-end text-gray-700 underline-offset-1 hover:text-gray-900'>
								<span className='group-hover:underline md:max-w-[32em] md:overflow-hidden md:text-ellipsis md:whitespace-nowrap block md:inline'>{item.title}</span>
								<span className='text-sm md:ml-8 ml-0 whitespace-nowrap  text-gray-400'>
									{item.create_time as string}
								</span>
							</a>
						</Link>
					);
				})}
			</div>
		</Layout>
	);
};

export default Home;
